name: gamboas graphics
favicon: null
layout_spectrum: 0.5043
typography_spectrum: 0.25064
title: Art by Andre Gamboa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fa9000'
    - '#1d3d67'
    - '#778aa5'
    - '#a4b1c3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
