name: gamboas graphics
favicon: null
layout_spectrum: 0.3049809511285275
typography_spectrum: 0.948838350828737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6200694649014622
  lightness: 0.8734696884639561
  saturation: 0.6338671108242124
  rhythmicContrast: 0.8326860063243657
purpose: []
